import React, { useEffect, useState } from 'react';
import { PageShell } from '../components/layout/PageShell';
import { DataTable } from '../components/ui/DataTable';
import { useReport } from '../hooks/useReport';
import { downloadReportCsv } from '../api/report';
import { useAuth } from '../context/AuthContext';

const MODULE_LABELS: Record<string, string> = {
  'M1-InternalTransactionRecords': 'M1 · Internal transaction records',
  'M2-PaymentGatewayRecords': 'M2 · Payment-gateway records',
  'M3-BankSettlementRecords': 'M3 · Bank settlement records',
  'M4-TransactionIDMatching': 'M4 · Transaction-ID matching',
  'M5-ReferenceMatching': 'M5 · Reference matching',
  'M6-PartialMatching': 'M6 · Partial matching',
  'M7-FeeCalculation': 'M7 · Fee calculation',
  'M8-RefundReversalHandling': 'M8 · Refund and reversal handling',
  'M9-SettlementMatching': 'M9 · Settlement matching',
  'M10-ExceptionManagement': 'M10 · Exception management',
  'M11-ReconciliationReport': 'M11 · Reconciliation report',
};

const moneyText = (value: string | number | null | undefined) => value == null || value === '' ? 'Not returned' : String(value);

export const ReportPage: React.FC = () => {
  const { user } = useAuth();
  const { report, loading, error, refresh } = useReport();
  const [exporting, setExporting] = useState(false);
  const [exportError, setExportError] = useState('');

  useEffect(() => { void refresh(); }, [refresh]);

  const exportCsv = async () => {
    if (!user?.token) return;
    setExporting(true); setExportError('');
    try {
      const csv = await downloadReportCsv(user.token);
      const url = URL.createObjectURL(new Blob([csv], { type: 'text/csv;charset=utf-8' }));
      const anchor = document.createElement('a');
      anchor.href = url;
      anchor.download = `ledgersense-${report?.reportId ?? 'report'}.csv`;
      document.body.appendChild(anchor); anchor.click(); anchor.remove(); URL.revokeObjectURL(url);
    } catch (caught) { setExportError(caught instanceof Error ? caught.message : 'The report export failed.'); }
    finally { setExporting(false); }
  };

  const totalOrders = report?.summary.totalOrdersIngested ?? 0;
  const matched = report?.summary.cleanMatchedOrders ?? 0;
  const matchRate = totalOrders > 0 ? `${((matched / totalOrders) * 100).toFixed(1)}%` : 'Not available';
  const moduleEntries = Object.entries(report?.moduleCoverage ?? {});

  const caseColumns = [
    { header: 'Case', accessor: (row: NonNullable<typeof report>['caseDetail'][number]) => <span className="font-mono text-xs">{row.caseId}</span> },
    { header: 'Order', accessor: (row: NonNullable<typeof report>['caseDetail'][number]) => <span className="font-mono text-xs">{row.orderId}</span> },
    { header: 'Type', accessor: (row: NonNullable<typeof report>['caseDetail'][number]) => row.type.replace(/_/g, ' ').toLowerCase() },
    { header: 'Amount at risk', accessor: (row: NonNullable<typeof report>['caseDetail'][number]) => <span className="font-mono text-rust">{row.amountAtRisk}</span> },
    { header: 'Status', accessor: (row: NonNullable<typeof report>['caseDetail'][number]) => row.status.replace(/_/g, ' ').toLowerCase() },
  ];

  return (
    <PageShell title="Reconciliation report" subtitle="A report snapshot returned by the API. Its module labels are not an external audit or compliance certification." actions={<>
      <button type="button" onClick={() => void refresh()} disabled={loading} className="touch-target border border-line bg-white px-4 text-sm font-semibold hover:border-ink disabled:opacity-50">{loading ? 'Refreshing…' : 'Refresh'}</button>
      <button type="button" onClick={() => void exportCsv()} disabled={exporting} className="touch-target bg-forest px-5 text-sm font-semibold text-white hover:bg-ink disabled:opacity-50">{exporting ? 'Preparing…' : 'Export CSV'}</button>
    </>}>
      {(error || exportError) && <div role="alert" className="border-l-2 border-rust bg-[#faf2ee] px-4 py-3 text-sm leading-6 text-rust">{error || exportError}</div>}
      {loading && !report && <div className="space-y-3" aria-live="polite"><div className="h-20 animate-pulse border border-line bg-white"/><div className="h-40 animate-pulse border border-line bg-white"/></div>}
      {!loading && !report && <div className="border border-line bg-white p-6 text-sm leading-6 text-muted">No report data was returned. Check the API connection, then refresh to try again.</div>}

      {report && <div className="space-y-7">
        <section className="flex flex-col justify-between gap-4 border-y border-line bg-white px-5 py-5 sm:flex-row sm:items-center sm:px-6">
          <div><p className="text-xs font-semibold uppercase tracking-[0.12em] text-muted">Report reference</p><p className="mt-2 break-all font-mono text-lg font-semibold">{report.reportId}</p><p className="mt-2 text-sm text-muted">Generated by {report.generatedBy || 'API'} · {new Date(report.generatedAt).toLocaleString('en-IN')}</p></div>
          <p className="max-w-md text-sm leading-6 text-muted">Values reflect the report response at the time shown. Confirm data-source mode and record provenance before relying on the figures.</p>
        </section>

        <section className="grid gap-0 border-y border-line bg-white sm:grid-cols-2 lg:grid-cols-4" aria-label="Report summary">
          {[
            ['Orders ingested', totalOrders.toLocaleString('en-IN')],
            ['Clean matches', matched.toLocaleString('en-IN')],
            ['Match share', matchRate],
            ['Cases needing review', (report.summary.discrepanciesFound ?? 0).toLocaleString('en-IN')],
          ].map(([label, value], index) => <div key={label} className={`px-4 py-5 sm:px-5 ${index ? 'border-t border-line sm:border-l sm:border-t-0' : ''}`}><p className="text-sm text-muted">{label}</p><p className="mt-3 text-2xl font-semibold tracking-[-0.03em]">{value}</p></div>)}
        </section>

        <section className="grid gap-7 lg:grid-cols-[1.1fr_0.9fr]">
          <div className="border border-line bg-white p-5 sm:p-6">
            <div className="border-b border-line pb-4"><h2 className="text-base font-semibold">Module status returned by API</h2><p className="mt-1 text-sm text-muted">Status labels describe this implementation response only.</p></div>
            <div className="divide-y divide-line">
              {moduleEntries.map(([key, details]) => <div key={key} className="flex flex-col justify-between gap-2 py-3 sm:flex-row sm:items-start">
                <div><p className="text-sm font-medium">{MODULE_LABELS[key] || key}</p><p className="mt-1 text-xs leading-5 text-muted">{details.method || details.algorithm || details.schedule || details.recordCount != null ? [details.method, details.algorithm, details.schedule, details.recordCount != null ? `${details.recordCount} records` : null].filter(Boolean).join(' · ') : 'No detail supplied.'}</p></div>
                <span className={`shrink-0 self-start border px-2.5 py-1 text-xs font-semibold ${details.status === 'IMPLEMENTED' ? 'border-[#c9dfd3] bg-[#f2f7f4] text-forest' : details.status === 'PARTIAL' ? 'border-[#e6d5b0] bg-[#f6f0e3] text-amber' : 'border-line bg-paper text-muted'}`}>{details.status.replace(/_/g, ' ').toLowerCase()}</span>
              </div>)}
              {!moduleEntries.length && <p className="py-5 text-sm text-muted">No module status details were returned.</p>}
            </div>
          </div>

          <div className="border border-line bg-white p-5 sm:p-6">
            <div className="border-b border-line pb-4"><h2 className="text-base font-semibold">Settlement comparison</h2><p className="mt-1 text-sm text-muted">Values returned by report calculation</p></div>
            <dl className="mt-2 divide-y divide-line">
              {[
                ['API status', report.settlementVerification.status.replace(/_/g, ' ').toLowerCase()],
                ['Gateway net', moneyText(report.settlementVerification.gatewayNetTotal)],
                ['Bank credit', moneyText(report.settlementVerification.bankCreditTotal)],
                ['Variance', moneyText(report.settlementVerification.variance)],
                ['Settled volume', moneyText(report.summary.totalSettled)],
                ['Amount at risk', moneyText(report.summary.totalAmountAtRisk)],
              ].map(([label, value]) => <div key={label} className="flex justify-between gap-4 py-3 text-sm"><dt className="text-muted">{label}</dt><dd className="text-right font-mono tabular-nums">{value}</dd></div>)}
            </dl>
          </div>
        </section>

        <section className="border border-line bg-white p-4 sm:p-6">
          <div className="mb-4"><h2 className="text-base font-semibold">Exception detail</h2><p className="mt-1 text-sm text-muted">Case records included in this report response.</p></div>
          <DataTable columns={caseColumns as any} rows={report.caseDetail as any[]} emptyMessage="No exception details were returned in this report." />
        </section>
      </div>}
    </PageShell>
  );
};
